# Generated by Django 5.2.6 on 2025-09-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('extra_info', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.DateTimeField()),
                ('buid_timeZone', models.CharField(default='UTC', max_length=50)),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence_time', models.DateTimeField(default=models.DateTimeField())),
                ('type', models.CharField(choices=[('meeting', 'meeting'), ('event', 'event'), ('first_appointment', 'first_appointment'), ('presentation', 'presentation')], max_length=50)),
                ('repeat_rule', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('occurrence_time', models.DateTimeField()),
                ('exception_type', models.CharField(choices=[('skip', 'Skip'), ('modify', 'Modify')], max_length=20)),
                ('new_start_time', models.DateTimeField(blank=True, null=True)),
                ('new_end_time', models.DateTimeField(blank=True, null=True)),
                ('new_title', models.CharField(blank=True, max_length=200, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('new_link', models.URLField(blank=True, null=True)),
                ('new_extra_info', models.CharField(blank=True, max_length=30, null=True)),
                ('new_note', models.TextField(blank=True, null=True)),
                ('new_type', models.CharField(blank=True, choices=[('meeting', 'meeting'), ('event', 'event'), ('first time appointment', 'first time appointment'), ('presentation', 'presentation')], max_length=50, null=True)),
                ('apply_range', models.CharField(choices=[('This time', 'This time'), ('This and future', 'This and future'), ('All time', 'All time')], default='This time')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='events.event')),
            ],
        ),
    ]
