# Generated by Django 5.2.6 on 2025-09-04 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('meeting', 'meeting'), ('event', 'event'), ('first time appointment', 'first time appointment'), ('presentation', 'presentation')], max_length=50)),
                ('repeat_rule', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateTimeField()),
                ('exception_type', models.CharField(choices=[('skip', 'Skip'), ('modify', 'Modify')], max_length=20)),
                ('new_start_time', models.DateTimeField(blank=True, null=True)),
                ('new_end_time', models.DateTimeField(blank=True, null=True)),
                ('new_title', models.CharField(blank=True, max_length=200, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='events.event')),
            ],
        ),
    ]
