# Generated by Django 5.2.6 on 2025-09-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexception',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventexception',
            name='new_extra_info',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventexception',
            name='new_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventexception',
            name='new_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventexception',
            name='new_type',
            field=models.CharField(blank=True, choices=[('meeting', 'meeting'), ('event', 'event'), ('first time appointment', 'first time appointment'), ('presentation', 'presentation')], max_length=50, null=True),
        ),
    ]
