# Generated by Django 5.2.6 on 2025-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_end_time_alter_event_occurrence_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
