# Generated by Django 5.2.6 on 2025-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventexception_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='buid_timeZone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
