# Generated by Django 5.2.6 on 2025-09-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_description_event_note_event_extra_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
