# Generated by Django 5.2.6 on 2025-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_buid_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('meeting', 'meeting'), ('event', 'event'), ('1st time appointment', '1st time appointment'), ('presentation', 'presentation')], max_length=50),
        ),
    ]
