# Generated by Django 5.2.6 on 2025-09-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sub_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
