# Generated by Django 5.2.6 on 2025-09-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexception',
            name='occurrence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
