# Generated by Django 5.2.6 on 2025-09-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('meeting', 'meeting'), ('event', 'event'), ('first_appointment', 'first_appointment'), ('presentation', 'presentation')], max_length=50),
        ),
    ]
