# Generated by Django 5.2.6 on 2025-09-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventexception',
            old_name='occurrence_date',
            new_name='occurrence_time',
        ),
    ]
