# Generated by Django 5.2.6 on 2025-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_occurrence_date_eventexception_occurrence_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexception',
            name='id',
        ),
        migrations.AddField(
            model_name='eventexception',
            name='sub_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
