# Generated by Django 5.2.6 on 2025-09-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventexception_id_eventexception_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexception',
            name='apply_range',
            field=models.CharField(choices=[('This time', 'This time'), ('This and future', 'This and future'), ('All time', 'All time')], default='only_this'),
        ),
    ]
